---
title: "Supplementary Analysis"
output:
  rmarkdown::pdf_document:
    extra_dependencies: ["float"]
    fig_caption: yes        
header-includes: 
  \usepackage{float} \floatplacement{figure}{H} 
  \newcommand{\beginsupplement}{\setcounter{table}{0}  \renewcommand{\thetable}{S\arabic{table}} \setcounter{figure}{0} \renewcommand{\thefigure}{S\arabic{figure}}}
editor_options: 
  chunk_output_type: console
---

\beginsupplement
```{r setup, echo=FALSE,message=FALSE, warning=FALSE, paged.print=FALSE}
# Load packages
library(BayesFactor)
library(reshape2)
library(ggplot2)
library(kableExtra)
library(lmerTest)
library(tidyverse)
library(jsonlite)
library(lubridate)
library(vroom)
library(countrycode)
library(gt)
library(janitor)
library(here)
library(ggrepel)

setwd("~/PSA-006-Trolley-problem")
trolley <- read_csv("data/trolley.csv",guess_max = 10000L)

```

```{r dem1,echo=FALSE,message=FALSE, warning=FALSE, paged.print=FALSE}

cd_raw <- read_csv(here::here("data/collectivism_similarity_matrix-from_culturaldistance.com.csv"))

cd <- 
  cd_raw %>% 
  transmute(country = names(.),
            Collectivism = `United States2010-2014`) %>% 
  extract(country, 
          into = c("Country", "distance_year"), 
          regex = "(.*)(\\d{4}-\\d{4})") %>% 
  # Get the latest similarity data
  group_by(Country) %>% 
  slice_tail(n = 1) %>% 
  ungroup() %>% 
  # USA should have 0 distance (not NA)
  mutate(Collectivism = if_else(is.na(Collectivism), 0, Collectivism),
         country3 = countryname(sourcevar = Country, 
                                destination = "iso3c")) 



```



#1. Exclusion 


```{r exclusion,echo=FALSE,message=FALSE, warning=FALSE, paged.print=FALSE}
all_responses <- 
  trolley %>% 
  count(Region, name = "all", .drop = TRUE)

exclude_careless <- 
  trolley %>% 
  filter(!include_nocareless) %>% 
  group_by(Region) %>% 
  summarise(Reason = "Careless responding", 
            n = n(), 
            .groups = "drop")

exclude_confusion <- 
  trolley %>% 
  filter(!include_noconfusion) %>% 
  group_by(Region) %>% 
  summarise(Reason = "Confusion",
            n = n(), 
            .groups = "drop")

exclude_familiar <- 
  trolley %>% 
  filter(!include_nofamiliarity) %>% 
  group_by(Region) %>% 
  summarise(Reason = "Familiarity of the research question",
            n = n(), 
            .groups = "drop")

exclude_techproblem <- 
  trolley %>% 
  filter(!include_notechproblem) %>% 
  group_by(Region) %>%   
  summarise(Reason = "Technical problem",
            n = n(), 
            .groups = "drop")

exclude_nonnative <- 
  trolley %>% 
  filter(!include_nonativelang) %>% 
  group_by(Region) %>%   
  summarise(Reason = "Non-native speaker",
            n = n(), 
            .groups = "drop")

exclude_study1a <- 
  trolley %>%
  filter(!include_study1a) %>% 
  group_by(Region) %>%   
  summarise(Reason = "Failed attention check (Study1a)",
            n = n(), 
            .groups = "drop")

exclude_study1b <- 
  trolley %>% 
  filter(!include_study1b) %>% 
  group_by(Region) %>%   
  summarise(Reason = "Failed attention check (Study1b)",
            n = n(), 
            .groups = "drop")

exclude_study2a <-
  trolley %>% 
  filter(!include_study2a) %>% 
  group_by(Region) %>% 
  summarise(Reason = "Failed attention check (Study2a)",
            n = n(), 
            .groups = "drop")

exclude_study2b <-
  trolley %>% 
  filter(!include_study2b) %>% 
  group_by(Region) %>%   
  summarise(Reason = "Failed attention check (Study2b)",
            n = n(), 
            .groups = "drop")

# Create a table with all included studies in 
all_wide <-
  bind_rows(tibble(study = "study1a", count(study1a, Region)),
            tibble(study = "study1b", count(study1b, Region)),
            tibble(study = "study2a", count(study2a, Region)),
            tibble(study = "study2b", count(study2b, Region))) %>% 
  pivot_wider(names_from = "Region", 
              values_from = "n", 
              names_prefix = "n_") %>% 
  mutate(info = "Final sample",
         n_All = n_Eastern + n_Southern + n_Western,
         Reason = str_glue("{str_to_sentence(study)}")) %>% 
  select(-study)

all_wide_wofamiliarity <-
  bind_rows(tibble(study = "study1a", count(study1a, Region)),
            tibble(study = "study1b", count(study1b, Region)),
            tibble(study = "study2a", count(study2a, Region)),
            tibble(study = "study2b", count(study2b, Region))) %>% 
  pivot_wider(names_from = "Region", 
              values_from = "n", 
              names_prefix = "n_") %>% 
  mutate(info = "Final sample",
         n_All = n_Eastern + n_Southern + n_Western,
         Reason = str_glue("{str_to_sentence(study)}")) %>% 
  select(-study)

exclude_all <-
  bind_rows(exclude_careless,
            exclude_confusion,
            exclude_familiar,
            exclude_techproblem,
            exclude_nonnative,
            exclude_study1a,
            exclude_study1b,
            exclude_study2a,
            exclude_study2b) %>% 
  left_join(all_responses, by = "Region") %>% 
  mutate(perc = n / all) %>% 
  select(-all) %>% 
  pivot_wider(names_from = "Region", 
              values_from = c(n, perc)) %>% 
  mutate(n_All = n_Eastern + n_Southern + n_Western,
         perc_All = n_All/nrow(trolley),
         info = "Reason to exclude")
  
# Exclusion reason by region (excluded participants can overlap!)
exclude_table <-
  exclude_all %>% 
  bind_rows(all_wide) %>% 
  group_by(info) %>% 
  gt() %>% 
  fmt_number(vars(n_Eastern, n_Southern, n_Western, n_All), 
             decimals = 0) %>%
  fmt_percent(columns = vars(perc_Eastern, perc_Southern, perc_Western, perc_All), decimals = 1) %>%
  fmt_missing(everything(), missing_text = "") %>%
  cols_merge(columns = vars(n_Eastern, perc_Eastern), 
             pattern = "{1} ({2})") %>% 
  cols_merge(columns = vars(n_Southern, perc_Southern), 
             pattern = "{1} ({2})") %>% 
  cols_merge(columns = vars(n_Western, perc_Western), 
           pattern = "{1} ({2})") %>% 
  cols_merge(columns = vars(n_All, perc_All), 
       pattern = "{1} ({2})") %>% 
  cols_label(Reason = " ",
             n_Eastern = "Eastern",
             n_Southern = "Southern",
             n_Western = "Western",
             n_All = "All") %>% 
  cols_align("left", columns = "Reason") %>%
  cols_align("right", columns = vars(n_Eastern, n_Southern, n_Western, n_All)) %>%
  tab_options(row.striping.include_table_body = TRUE,
              row.striping.background_color = "#EEEEEE", 
              row.striping.include_stub = TRUE,
              row_group.background.color = "#999999", 
              column_labels.background.color = "#999999") %>% 
  text_transform(locations = cells_body(
                 columns = vars(n_Eastern, n_Southern, n_Western, n_All)),
                          fn = function(x) {if_else(str_detect(x, "()"), 
                                        str_remove(x, "\\(\\)"),
                                        x)})

exclude_table
```



#2. Main replication analysis

##Study 1a and 1b
```{r individualism score, echo=FALSE,message=FALSE, warning=FALSE, paged.print=FALSE}

trolley=merge(trolley,cd, by="country3", all=T)
trolley<-trolley[!is.na(trolley$survey_name),]


attach(trolley)
trolley$hor_ind=rowMeans(cbind(individualism_scale_1, individualism_scale_2,individualism_scale_3,individualism_scale_4))
trolley$ver_ind=rowMeans(cbind(individualism_scale_5, individualism_scale_6,individualism_scale_7,individualism_scale_8))
trolley$hor_col=rowMeans(cbind(individualism_scale_9, individualism_scale_10,individualism_scale_11,individualism_scale_12))
trolley$ver_col=rowMeans(cbind(individualism_scale_13, individualism_scale_14,individualism_scale_15,individualism_scale_16))
detach(trolley)

study1a <- filter(trolley, include_study1a)
study1b <- filter(trolley, include_study1b)
study2a <- filter(trolley, include_study2a)
study2b <- filter(trolley, include_study2b)

trolley_proc <- filter(trolley, include_allstudy_withoutfamiliarity)

trolley_familiar <- filter(trolley_proc, !include_nofamiliarity)



survey=levels(factor(trolley_proc$survey_name))




#cor.test(trolley_proc$hor_col, trolley_proc$familiarity)
#correlationBF(trolley_proc$hor_col, trolley_proc$familiarity)

```


###Bayesian analysis

```{r Study1a Bayesian, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}

#use data study1a
tabledata_s1a = data.frame(Exclusion=c(rep("Exclusion",3)),Cluster=c("Eastern", "Southern", "Western"), matrix(nrow=3, ncol=5, dimnames=list(survey,c("BF","RR", "t", "df", "p"))))

for (i in survey){
dat=subset(study1a, survey_name==i, select=c("trolley_1_rate", "trolley_2_rate"))
dat_long=na.omit(melt(data=dat, variable.name = "condition", value.name="rate"))
datt=as_tibble(ttestBF(formula = rate ~ condition, data=dat_long, rscale=0.26, nullInterval = c(0, Inf)))
tabledata_s1a[i, "BF"]=signif(round(as.numeric(datt[2,1]),1),2)
frequentist=t.test(rate ~ condition, data=dat_long)
tabledata_s1a[i, "t"]=round(frequentist$statistic,2)
tabledata_s1a[i, "df"]=round(frequentist$parameter,2)
tabledata_s1a[i, "p"]=round(frequentist$p.value,4)
tabledata_s1a[i, "Cohen d"]=round(effsize::cohen.d(rate ~ condition, data=dat_long)[[3]] ,2)
}

tabledata_s1a_ne = data.frame(Exclusion=c(rep("Including familiar",3)),Cluster=c("Eastern", "Southern", "Western"), matrix(nrow=3, ncol=5, dimnames=list(survey,c("BF","RR", "t", "df", "p"))))
for (i in survey){
dat=subset(trolley_proc, survey_name==i, select=c("trolley_1_rate", "trolley_2_rate"))
dat_long=na.omit(melt(data=dat, variable.name = "condition", value.name="rate"))
datt=as_tibble(ttestBF(formula = rate ~ condition, data=dat_long, rscale=0.26, nullInterval = c(0, Inf)))
tabledata_s1a_ne[i, "BF"]=signif(round(as.numeric(datt[2,1]),1),2)
frequentist=t.test(rate ~ condition, data=dat_long)
tabledata_s1a_ne[i, "t"]=round(frequentist$statistic,2)
tabledata_s1a_ne[i, "df"]=round(frequentist$parameter,2)
tabledata_s1a_ne[i, "p"]=round(frequentist$p.value,4)
tabledata_s1a_ne[i, "Cohen d"]=round(effsize::cohen.d(rate ~ condition, data=dat_long)[[3]] ,2)
}
studys1a_results = rbind(tabledata_s1a, tabledata_s1a_ne)
rownames(studys1a_results) <- NULL
studys1a_results$p=if_else(as.numeric(p) < .001, "< .001", p)

studys1a_results[,"RR"]<-c("7.00e-03, 14.00", "1.00e-05, 2.80e+06", "1.20e-02, 4.30", "<1.00e-05, 1.10e+04", "<1.00e-05, 6.30e+14", "<1.00e-05, 9.80e+07")

kbl(
  studys1a_results,
  format = "latex",
  booktabs = T,
  escape=T,
  caption = "The effect of personal force on moral dilemma judgements on Trolley dilemmas",
  centering=T,
  position="H"
  )%>%
  kable_styling( full_width = F,  position="left")%>%
  row_spec(row=0, bold=TRUE)%>%
  collapse_rows(columns = 1, valign = "top", latex_hline = "major", row_group_label_position = "identity")

```


<!-- //graph with exclusion -->
```{r Study1a excl graph, fig.pos = "H" ,out.width = "80%", fig.cap = "Results on Trolley dilemmas in Study 1 with all exclusion criteria applied. Black full circles indicate group level means.", echo = FALSE, message = FALSE, warning = FALSE, paged.print = FALSE }
# Load violin plot function
source("https://gist.githubusercontent.com/benmarwick/2a1bb0133ff568cbe28d/raw/fb53bd97121f7f9ce947837ef1a4c65a73bffb3f/geom_flat_violin.R")

# Prepare data for plotting
plot_data <- 
  study1a %>% 
  select(survey_name, trolley_1_rate, trolley_2_rate) %>% 
  mutate(survey_name = factor(survey_name)) %>% 
  pivot_longer(
    - survey_name,
    names_to = "condition",
    values_to = "rate") %>% 
  mutate(condition = case_when(condition == "trolley_1_rate" ~ "Personal Force",
                               condition == "trolley_2_rate" ~ "No personal force"),
         condition = factor(condition, levels = c("Personal Force", "No personal force")),
         survey_name = str_remove(survey_name, "PSA006_")) %>% 
  drop_na(rate)

sumld <- 
  plot_data %>% 
  group_by(survey_name, condition) %>% 
  summarise(mean = mean(rate, na.rm = T),
            median = median(rate, na.rm = T),
            sd = sd(rate, na.rm = T),
            lower = mean - sd,
            upper = mean + sd)

# Create plot
plot_data %>% 
  ggplot() +
  aes(
    x = condition,
    y = rate,
    fill = condition) +
  geom_flat_violin(
    position = position_nudge(x = 0, y = 0),
    alpha = .8) +
  #geom_point(aes(y = rate, color = condition), position = position_jitter(width = .15), size = .5, alpha = 0.8) +
  stat_summary(
    fun = mean,
    geom = "line",
    aes(group = 1),
    position = position_nudge(x = 0.1),
    size = 1) +
  geom_line(
    data = sumld,
    aes(x = condition, y = mean),
    position = position_nudge(x = 0.1),
    size = 2.5) +
  geom_point(
    data = sumld,
    aes(x = condition, y = mean),
    position = position_nudge(x = 0.1),
    size = 2.5) +
  #geom_errorbar(data = sumld, aes(ymin = lower, ymax = upper, y = mean), position = position_nudge(x = 0.3), width = 0) +
  guides(fill = FALSE) +
  guides(color = FALSE) +
  scale_fill_viridis_d() +
  facet_wrap(facets = vars(survey_name)) +
  labs(y = "To what extent is this action morally acceptable?") +
  theme_bw() +
  expand_limits(y = c(1,9)) + 
  scale_y_continuous(breaks = 1:9) +
  theme(
    panel.grid.major=element_blank(),
    panel.grid.minor=element_blank(),
    plot.title=element_text(hjust = 0.5, vjust = 0.5, face = "bold", size = 17),
    axis.title.x=element_blank(),
    axis.title.y=element_text(face = "bold", size = 10),
    axis.text.x = element_text(face = "bold", size = 7, colour = "Black"),
    axis.text.y = element_text(face = "bold", size = 12, colour = "Black"),
    legend.title=element_blank(),
    legend.text=element_text(size = 9))
```


<!-- //graph without exclusion -->
```{r Study1a w/o excl graph, fig.pos = "H",out.width = "80%",fig.cap = "Results on Trolley dilemmas in Study 1 with no exclusion criteria applied. Black full circles indicate group level means.", echo = FALSE, message = FALSE, warning = FALSE, paged.print = FALSE }
# Prepare data for plotting
plot_data <- 
  trolley_proc %>% 
  select(survey_name, trolley_1_rate, trolley_2_rate) %>% 
  mutate(survey_name = factor(survey_name)) %>% 
  pivot_longer(
    -survey_name,
    names_to = "condition",
    values_to = "rate") %>% 
  mutate(condition = case_when(condition == "trolley_1_rate" ~ "Personal Force",
                               condition == "trolley_2_rate" ~ "No personal force"),
         condition = factor(condition, levels = c("Personal Force", "No personal force")),
         survey_name = str_remove(survey_name, "PSA006_")) %>% 
  drop_na(rate)

sumld <- 
  plot_data %>% 
  group_by(survey_name, condition) %>% 
  summarise(mean = mean(rate, na.rm = T),
            median = median(rate, na.rm = T),
            sd = sd(rate, na.rm = T),
            lower = mean - sd,
            upper = mean + sd)

# Create plot
plot_data %>% 
  ggplot() +
  aes(
    x = condition,
    y = rate,
    fill = condition) +
  geom_flat_violin(
    position = position_nudge(x = 0, y = 0),
    alpha = .8)+
  #geom_point(aes(y = rate, color = condition), position = position_jitter(width = .15), size = .5, alpha = 0.8) +
  stat_summary(
    fun = mean,
    geom = "line",
    aes(group = 1),
    position = position_nudge(x = 0.1),
    size = 1) +
  geom_line(
    data = sumld,
    aes(x = condition, y = mean),
    position = position_nudge(x = 0.1),
    size = 2.5) +
  geom_point(
    data = sumld,
    aes(x = condition, y = mean),
    position = position_nudge(x = 0.1),
    size = 2.5) +
  guides(fill = FALSE) +
  guides(color = FALSE) +
  scale_fill_viridis_d() +
  facet_wrap(facets = vars(survey_name)) +
  labs(y = "To what extent is this action morally acceptable?") +
  theme_bw() +
  expand_limits(y = c(1,9)) + 
  scale_y_continuous(breaks = 1:9) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_text(hjust = 0.5, vjust = 0.5, face = "bold", size = 17),
    axis.title.x = element_blank(),
    axis.title.y = element_text(face = "bold", size = 10),
    axis.text.x = element_text(face = "bold", size = 7, colour = "Black"),
    axis.text.y = element_text(face = "bold", size = 12, colour = "Black"),
    legend.title = element_blank(),
    legend.text = element_text(size = 9))
```

```{r Study1b Bayesian, echo=FALSE,message=FALSE, warning=FALSE, paged.print=FALSE}

survey=levels(factor(trolley_proc$survey_name))
tabledata_s1b = data.frame(Exclusion=c(rep("Exclusion",3)),Cluster=c("Eastern", "Southern", "Western"), matrix(nrow=3, ncol=5, dimnames=list(survey,c("BF","RR", "t", "df", "p"))))

for (i in survey){
dat=subset(study1b, survey_name==i, select=c("speedboat_1_rate", "speedboat_2_rate"))
dat_long=na.omit(melt(data=dat, variable.name = "condition", value.name="rate"))
datt=as_tibble(ttestBF(formula = rate ~ condition, data=dat_long, rscale=0.26, nullInterval = c(0, Inf)))
tabledata_s1b[i, "BF"]=signif(round(as.numeric(datt[2,1]),1),2)
frequentist=t.test(rate ~ condition, data=dat_long)
tabledata_s1b[i, "t"]=round(frequentist$statistic,2)
tabledata_s1b[i, "df"]=round(frequentist$parameter,2)
tabledata_s1b[i, "p"]=round(frequentist$p.value,3)
tabledata_s1b[i, "Cohen d"]=round(effsize::cohen.d(rate ~ condition, data=dat_long)[[3]] ,2)

}

tabledata_s1b_ne = data.frame(Exclusion=c(rep("Including familiar",3)),Cluster=c("Eastern", "Southern", "Western"), matrix(nrow=3, ncol=5, dimnames=list(survey,c("BF","RR", "t", "df", "p"))))
for (i in survey){
dat=subset(trolley_proc, survey_name==i, select=c("speedboat_1_rate", "speedboat_2_rate"))
dat_long=na.omit(melt(data=dat, variable.name = "condition", value.name="rate"))
datt=as_tibble(ttestBF(formula = rate ~ condition, data=dat_long, rscale=0.26, nullInterval = c(0, Inf)))
tabledata_s1b_ne[i, "BF"]=signif(round(as.numeric(datt[2,1]),1),2)
frequentist=t.test(rate ~ condition, data=dat_long)
tabledata_s1b_ne[i, "t"]=round(frequentist$statistic,2)
tabledata_s1b_ne[i, "df"]=round(frequentist$parameter,2)
tabledata_s1b_ne[i, "p"]=round(frequentist$p.value,3)
tabledata_s1b_ne[i, "Cohen d"]=round(effsize::cohen.d(rate ~ condition, data=dat_long)[[3]] ,2)

}
studys1b_results = rbind(tabledata_s1b, tabledata_s1b_ne)
rownames(studys1b_results) <- NULL
studys1a_results$p=if_else(as.numeric(p) < .001, "< .001", p)

studys1b_results[,"RR"]<-c("1.50e-0.3, 1.70e+04", "1.30e-03, 74.00", "3.30e-02, 1.2", "<1.00e-05, 9.50e+03", "<1.00e-05, 2.10e+08", "<1.00e-05, 1.0e+08")

kbl(
  studys1b_results,
  format = "latex",
  booktabs = T,
  escape=T,
  caption = " The effect of personal force on moral dilemma judgements on Speedboat dilemmas",
  centering=T,
  position="H"
  )%>%
  kable_styling( full_width = F,  position="left")%>%
  row_spec(row=0, bold=TRUE)%>%
  collapse_rows(columns = 1, valign = "top", latex_hline = "major", row_group_label_position = "identity")
```


<!-- //graph with exclusion -->
```{r Study1b excl graph, fig.pos="H",out.width="80%",fig.cap="Results on Trolley dilemmas in Study 1 with all exclusion criteria applied. Black full circles indicate group level means.", echo =FALSE,message=FALSE, warning=FALSE, paged.print=FALSE }
# Prepare data for plotting
plot_data <- 
  study1b %>% 
  select(survey_name, speedboat_1_rate, speedboat_2_rate) %>% 
  mutate(survey_name = factor(survey_name)) %>% 
  pivot_longer(
    -survey_name,
    names_to = "condition",
    values_to = "rate") %>% 
  mutate(condition = case_when(condition == "speedboat_1_rate" ~ "Personal Force",
                               condition == "speedboat_2_rate" ~ "No personal force"),
         condition = factor(condition, levels = c("Personal Force", "No personal force")),
         survey_name = str_remove(survey_name, "PSA006_")) %>% 
  drop_na(rate)

sumld <- 
  plot_data %>% 
  group_by(survey_name, condition) %>% 
  summarise(mean = mean(rate, na.rm = T),
            median = median(rate, na.rm = T),
            sd = sd(rate, na.rm = T),
            lower = mean - sd,
            upper = mean + sd)

# Create plot
plot_data %>% 
  ggplot() +
  aes(
    x = condition,
    y = rate,
    fill = condition) +
  geom_flat_violin(
    position = position_nudge(x = 0, y = 0),
    alpha = .8)+
  #geom_point(aes(y = rate, color = condition), position = position_jitter(width = .15), size = .5, alpha = 0.8) +
  stat_summary(
    fun = mean,
    geom = "line",
    aes(group = 1),
    position = position_nudge(x = 0.1),
    size = 1) +
  geom_line(
    data = sumld,
    aes(x = condition, y = mean),
    position = position_nudge(x = 0.1),
    size = 2.5) +
  geom_point(
    data = sumld,
    aes(x = condition, y = mean),
    position = position_nudge(x = 0.1),
    size = 2.5) +
  guides(fill = FALSE) +
  guides(color = FALSE) +
  scale_fill_viridis_d() +
  facet_wrap(facets = vars(survey_name)) +
  labs(y = "To what extent is this action morally acceptable?") +
  theme_bw() +
  expand_limits(y = c(1,9)) + 
  scale_y_continuous(breaks = 1:9) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_text(hjust = 0.5, vjust = 0.5, face = "bold", size = 17),
    axis.title.x = element_blank(),
    axis.title.y = element_text(face = "bold", size = 10),
    axis.text.x = element_text(face = "bold", size = 7, colour = "Black"),
    axis.text.y = element_text(face = "bold", size = 12, colour = "Black"),
    legend.title = element_blank(),
    legend.text = element_text(size = 9))
```


<!-- //graph without exclusion -->
```{r Study1b w/o excl graph, fig.pos="H",out.width="80%",fig.cap="Results on Speedboat dilemmas in Study 1 with no exclusion criteria applied. Black full circles indicate group level means.", echo =FALSE,message=FALSE, warning=FALSE, paged.print=FALSE }
# Prepare data for plotting
plot_data <- 
  trolley_proc %>% 
  select(survey_name, speedboat_1_rate, speedboat_2_rate) %>% 
  mutate(survey_name = factor(survey_name)) %>% 
  pivot_longer(
    -survey_name,
    names_to = "condition",
    values_to = "rate") %>% 
  mutate(condition = case_when(condition == "speedboat_1_rate" ~ "Personal Force",
                               condition == "speedboat_2_rate" ~ "No personal force"),
         condition = factor(condition, levels = c("Personal Force", "No personal force")),
         survey_name = str_remove(survey_name, "PSA006_")) %>% 
  drop_na(rate)

sumld <- 
  plot_data %>% 
  group_by(survey_name, condition) %>% 
  summarise(mean = mean(rate, na.rm = T),
            median = median(rate, na.rm = T),
            sd = sd(rate, na.rm = T),
            lower = mean - sd,
            upper = mean + sd)

# Create plot
plot_data %>% 
  ggplot() +
  aes(
    x = condition,
    y = rate,
    fill = condition) +
  geom_flat_violin(
    position = position_nudge(x = 0, y = 0),
    alpha = .8)+
  #geom_point(aes(y = rate, color = condition), position = position_jitter(width = .15), size = .5, alpha = 0.8) +
  stat_summary(
    fun = mean,
    geom = "line",
    aes(group = 1),
    position = position_nudge(x = 0.1),
    size = 1) +
  geom_line(
    data = sumld,
    aes(x = condition, y = mean),
    position = position_nudge(x = 0.1),
    size = 2.5) +
  geom_point(
    data = sumld,
    aes(x = condition, y = mean),
    position = position_nudge(x = 0.1),
    size = 2.5) +
  guides(fill = FALSE) +
  guides(color = FALSE) +
  scale_fill_viridis_d() +
  facet_wrap(facets = vars(survey_name)) +
  labs(y = "To what extent is this action morally acceptable?") +
  theme_bw() +
  expand_limits(y = c(1,9)) + 
  scale_y_continuous(breaks = 1:9) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_text(hjust = 0.5, vjust = 0.5, face = "bold", size = 17),
    axis.title.x = element_blank(),
    axis.title.y = element_text(face = "bold", size = 10),
    axis.text.x = element_text(face = "bold", size = 7, colour = "Black"),
    axis.text.y = element_text(face = "bold", size = 12, colour = "Black"),
    legend.title = element_blank(),
    legend.text = element_text(size = 9))
```


##Study 2a and 2b

```{r Study2a Bayesian, echo=FALSE,message=FALSE, warning=FALSE, paged.print=FALSE}

tabledata_s2a = data.frame(Exclusion=c(rep("Exclusion",3)),Cluster=c("Eastern", "Southern", "Western"), matrix(nrow=3, ncol=5, dimnames=list(survey,c("BF","RR", "F", "df", "p"))))

for (i in survey){
dat=subset(study2a, survey_name==i, select=c("trolley_3_rate", "trolley_4_rate", "trolley_5_rate", "trolley_6_rate"))
dat_long=na.omit(melt(data=dat, measure.vars=c("trolley_3_rate", "trolley_4_rate", "trolley_5_rate", "trolley_6_rate"), variable.name = "condition", value.name="rate"))
dat_long$personal_force = factor(ifelse(dat_long$condition=="trolley_3_rate"|dat_long$condition=="trolley_5_rate", 0, 1))
dat_long$intention = factor(ifelse(dat_long$condition=="trolley_4_rate"|dat_long$condition=="trolley_5_rate", 1, 0))
datt=lmBF(rate ~ personal_force*intention, data=dat_long, rscaleFixed=c("personal_force:intention"=0.19))
datt2=lmBF(rate ~ personal_force+intention, data=dat_long)
datt3=datt/datt2
datt3=as_tibble(recompute(datt3, iterations = 50000))
tabledata_s2a[i, "BF"]=signif(round(datt3[1,1],1),2)
frequentist=summary(aov(rate ~ personal_force*intention, data=dat_long))[[1]]
tabledata_s2a[i, "F"]=round(frequentist[3, "F value"],3)
tabledata_s2a[i, "df"]=paste("1, ", frequentist[4, "Df"])
tabledata_s2a[i, "p"]=round(frequentist[3, "Pr(>F)"],3)
tabledata_s2a[i, "Eta squared"]=round(DescTools::EtaSq(aov(rate ~ personal_force*intention, data=dat_long))[3,2],3)
tabledata_s2a[i, "Raw effect"]=round((mean(dat_long[dat_long$personal_force==0 & dat_long$intention==0,]$rate,na.rm=T) - mean(dat_long[dat_long$personal_force==1 & dat_long$intention==0,]$rate,na.rm=T)) - (mean(dat_long[dat_long$personal_force==0 & dat_long$intention==1,]$rate,na.rm=T) - mean(dat_long[dat_long$personal_force==1 & dat_long$intention==1,]$rate,na.rm=T)),2) 
}

tabledata_s2a_ne = data.frame(Exclusion=c(rep("Including familiar",3)),Cluster=c("Eastern", "Southern", "Western"), matrix(nrow=3, ncol=5, dimnames=list(survey,c("BF","RR", "F", "df", "p"))))
for (i in survey){
dat=subset(trolley_proc, survey_name==i, select=c("trolley_3_rate", "trolley_4_rate", "trolley_5_rate", "trolley_6_rate"))
dat_long=na.omit(melt(data=dat, variable.name = "condition", value.name="rate"))
dat_long$personal_force = factor(ifelse(dat_long$condition=="trolley_3_rate"|dat_long$condition=="trolley_5_rate", 0, 1))
dat_long$intention = factor(ifelse(dat_long$condition=="trolley_4_rate"|dat_long$condition=="trolley_5_rate", 1, 0))
datt=lmBF(rate ~ personal_force*intention, data=dat_long, rscaleFixed=c("personal_force:intention"=0.19))
datt2=lmBF(rate ~ personal_force+intention, data=dat_long)
datt3=datt/datt2
datt3=as_tibble(recompute(datt3, iterations = 50000))
tabledata_s2a_ne[i, "BF"]=signif(round(datt3[1,1],1),2)
frequentist=summary(aov(rate ~ personal_force*intention, data=dat_long))[[1]]
tabledata_s2a_ne[i, "F"]=round(frequentist[3, "F value"],3)
tabledata_s2a_ne[i, "df"]=paste("1, ", frequentist[4, "Df"])
tabledata_s2a_ne[i, "p"]=round(frequentist[3, "Pr(>F)"],3)
tabledata_s2a_ne[i, "Eta squared"]=round(DescTools::EtaSq(aov(rate ~ personal_force*intention, data=dat_long))[3,2],3)
tabledata_s2a_ne[i, "Raw effect"]=round((mean(dat_long[dat_long$personal_force==0 & dat_long$intention==0,]$rate,na.rm=T) - mean(dat_long[dat_long$personal_force==1 & dat_long$intention==0,]$rate,na.rm=T)) - (mean(dat_long[dat_long$personal_force==0 & dat_long$intention==1,]$rate,na.rm=T) - mean(dat_long[dat_long$personal_force==1 & dat_long$intention==1,]$rate,na.rm=T)),2) 

}
studys2a_results = rbind(tabledata_s2a, tabledata_s2a_ne)
rownames(studys2a_results) <- NULL
studys2a_results[,"RR"]<-c("0.03, 0.64", "0.03, 0.2", "6.00e-05, 1.80e+03", "2.50e-02, 0.91", "8.00e-05, 1.70e+03", "<1.00e-05, 2.30e+14")


kbl(
  studys2a_results,
  format = "latex",
  booktabs = T,
  escape=T,
  caption = "Do personal force interact with intention on Trolley dilemmas?",
  centering=T,
  position="H"
  )%>%
  kable_styling( full_width = F,  position="left", latex_options = "scale_down")%>%
  row_spec(row=0, bold=TRUE)%>%
  collapse_rows(columns = 1, valign = "top", latex_hline = "major", row_group_label_position = "identity")

```

<!-- //graph with exclusion -->
```{r Study2a excl graph,fig.pos="H",out.width="80%",fig.cap="Results on Trolley dilemmas in Study 2 when all exclusion criteria are applied. Error bars are 95\\% confidence intervals on the mean.", echo =FALSE,message=FALSE, warning=FALSE, paged.print=FALSE }
# Prepare data for plotting
plot_data <- 
  study2a %>% 
  select(survey_name, trolley_3_rate, trolley_4_rate, trolley_5_rate, trolley_6_rate) %>% 
  mutate(survey_name = factor(survey_name)) %>% 
  pivot_longer(
    -survey_name,
    names_to = "condition",
    values_to = "rate") %>% 
  mutate(personal_force = case_when(condition == "trolley_3_rate" ~ "No Personal Force",
                                    condition == "trolley_4_rate" ~ "Personal force",
                                    condition == "trolley_5_rate" ~ "No Personal Force",
                                    condition == "trolley_6_rate" ~ "Personal force"),
         intention = case_when(condition == "trolley_3_rate" ~ "No Intention",
                               condition == "trolley_4_rate" ~ "Intention",
                               condition == "trolley_5_rate" ~ "Intention",
                               condition == "trolley_6_rate" ~ "No Intention"),
         intention = factor(intention, levels = c("No Intention", "Intention")),
         survey_name = str_remove(survey_name, "PSA006_")) %>% 
  drop_na(rate)

# Create plot
plot_data %>% 
  ggplot() +
  aes(
    x = intention,
    y = rate,
    fill = personal_force,
    width = 0.7) +
  stat_summary(
    fun = mean,
    geom = "bar",
    position = "dodge",
    colour = "Black",
    width = 1.2) +
  stat_summary(
    fun.data = mean_cl_boot,
    geom = "errorbar",
    position = position_dodge(width = 0.7),
    colour = "Black",
    width = 0.2) +
  scale_fill_viridis_d() +
  facet_wrap(facets=vars(survey_name)) +
  labs(y = "To what extent is this action morally acceptable?") +
  theme_bw() +
  expand_limits(y = c(1,9)) +
  scale_y_continuous(breaks = 1:9) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_text(hjust = 0.5, vjust = 0.5, face = "bold", size = 17),
    axis.title.x = element_blank(),
    axis.title.y = element_text(face = "bold", size = 10),
    axis.text.x = element_text(face = "bold", size = 7, colour = "Black"),
    axis.text.y = element_text(face = "bold", size = 12, colour = "Black"),
    legend.title = element_blank(),
    legend.text = element_text(size = 9))
```

<!-- //graph without exclusion -->
```{r Study2a w/o excl graph, fig.pos="H",out.width="80%",fig.cap="Results on Trolley dilemmas in Study 2 when no exclusion criteria are applied. Error bars are 95\\% confidence intervals on the mean. ",  echo =FALSE,message=FALSE, warning=FALSE, paged.print=FALSE }
# Prepare data for plotting
plot_data <- 
  trolley_proc %>% 
  select(survey_name, trolley_3_rate, trolley_4_rate, trolley_5_rate, trolley_6_rate) %>% 
  mutate(survey_name = factor(survey_name)) %>% 
  pivot_longer(
    -survey_name,
    names_to = "condition",
    values_to = "rate") %>% 
  mutate(personal_force = case_when(condition == "trolley_3_rate" ~ "No Personal Force",
                                    condition == "trolley_4_rate" ~ "Personal force",
                                    condition == "trolley_5_rate" ~ "No Personal Force",
                                    condition == "trolley_6_rate" ~ "Personal force"),
         intention = case_when(condition == "trolley_3_rate" ~ "No Intention",
                               condition == "trolley_4_rate" ~ "Intention",
                               condition == "trolley_5_rate" ~ "Intention",
                               condition == "trolley_6_rate" ~ "No Intention"),
         intention = factor(intention, levels = c("No Intention", "Intention")),
         survey_name = str_remove(survey_name, "PSA006_")) %>% 
  drop_na(rate)

# Create plot
plot_data %>% 
  ggplot() +
  aes(
    x = intention,
    y = rate,
    fill = personal_force,
    width = 0.7) +
  stat_summary(
    fun = mean,
    geom = "bar",
    position = "dodge",
    colour = "Black",
    width = 1.2) +
  stat_summary(
    fun.data = mean_cl_boot,
    geom = "errorbar",
    position = position_dodge(width = 0.7),
    colour = "Black",
    width = 0.2) +
  scale_fill_viridis_d() +
  facet_wrap(facets=vars(survey_name)) +
  labs(y = "To what extent is this action morally acceptable?") +
  theme_bw() +
  expand_limits(y = c(1,9)) +
  scale_y_continuous(breaks = 1:9) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_text(hjust = 0.5, vjust = 0.5, face = "bold", size = 17),
    axis.title.x = element_blank(),
    axis.title.y = element_text(face = "bold", size = 10),
    axis.text.x = element_text(face = "bold", size = 7, colour = "Black"),
    axis.text.y = element_text(face = "bold", size = 12, colour = "Black"),
    legend.title = element_blank(),
    legend.text = element_text(size = 9))
```

```{r study2b Bayesian, echo=FALSE,message=FALSE, warning=FALSE, paged.print=FALSE}
tabledata_s2b = data.frame(Exclusion=c(rep("Exclusion",3)),Cluster=c("Eastern", "Southern", "Western"), matrix(nrow=3, ncol=5, dimnames=list(survey,c("BF","RR", "F", "df", "p"))))
##ggrepel grom_text repel
for (i in survey){
dat=subset(study2b, survey_name==i, select=c("speedboat_3_rate", "speedboat_4_rate", "speedboat_5_rate", "speedboat_6_rate"))
dat_long=na.omit(melt(data=dat, variable.name = "condition", value.name="rate"))
dat_long$personal_force = factor(ifelse(dat_long$condition=="speedboat_3_rate"|dat_long$condition=="speedboat_5_rate", 0, 1))
dat_long$intention = factor(ifelse(dat_long$condition=="speedboat_4_rate"|dat_long$condition=="speedboat_5_rate", 1, 0))
datt=lmBF(rate ~ personal_force*intention, data=dat_long, rscaleFixed=c("personal_force:intention"=0.19))
datt2=lmBF(rate ~ personal_force+intention, data=dat_long)
datt3=datt/datt2
datt3=as_tibble(recompute(datt3, iterations = 50000))
tabledata_s2b[i, "BF"]=signif(round(datt3[1,1],1),2)
frequentist=summary(aov(rate ~ personal_force*intention, data=dat_long))[[1]]
tabledata_s2b[i, "F"]=round(frequentist[3, "F value"],3)
tabledata_s2b[i, "df"]=paste("1, ", frequentist[4, "Df"])
tabledata_s2b[i, "p"]=round(frequentist[3, "Pr(>F)"],3)
tabledata_s2b[i, "Eta squared"]=round(DescTools::EtaSq(aov(rate ~ personal_force*intention, data=dat_long))[3,2],3)
tabledata_s2b[i, "Raw effect"]=round((mean(dat_long[dat_long$personal_force==0 & dat_long$intention==0,]$rate,na.rm=T) - mean(dat_long[dat_long$personal_force==1 & dat_long$intention==0,]$rate,na.rm=T)) - (mean(dat_long[dat_long$personal_force==0 & dat_long$intention==1,]$rate,na.rm=T) - mean(dat_long[dat_long$personal_force==1 & dat_long$intention==1,]$rate,na.rm=T)),2) 
}

tabledata_s2b_ne = data.frame(Exclusion=c(rep("Including familiar",3)),Cluster=c("Eastern", "Southern", "Western"), matrix(nrow=3, ncol=5, dimnames=list(survey,c("BF","RR", "F", "df", "p"))))
for (i in survey){
dat=subset(trolley_proc, survey_name==i, select=c("speedboat_3_rate", "speedboat_4_rate", "speedboat_5_rate", "speedboat_6_rate"))
dat_long=na.omit(melt(data=dat, variable.name = "condition", value.name="rate"))
dat_long$personal_force = factor(ifelse(dat_long$condition=="speedboat_3_rate"|dat_long$condition=="speedboat_5_rate", 0, 1))
dat_long$intention = factor(ifelse(dat_long$condition=="speedboat_4_rate"|dat_long$condition=="speedboat_5_rate", 1, 0))
datt=lmBF(rate ~ personal_force*intention, data=dat_long, rscaleFixed=c("personal_force:intention"=0.19))
datt2=lmBF(rate ~ personal_force+intention, data=dat_long)
datt3=datt/datt2
datt3=as_tibble(recompute(datt3, iterations = 50000))
tabledata_s2b_ne[i, "BF"]=signif(round(datt3[1,1],1),2)
frequentist=summary(aov(rate ~ personal_force*intention, data=dat_long))[[1]]
tabledata_s2b_ne[i, "F"]=round(frequentist[3, "F value"],3)
tabledata_s2b_ne[i, "df"]=paste("1, ", frequentist[4, "Df"])
tabledata_s2b_ne[i, "p"]=round(frequentist[3, "Pr(>F)"],3)
tabledata_s2b_ne[i, "Eta squared"]=round(DescTools::EtaSq(aov(rate ~ personal_force*intention, data=dat_long))[3,2],3)
tabledata_s2b_ne[i, "Raw effect"]=round((mean(dat_long[dat_long$personal_force==0 & dat_long$intention==0,]$rate,na.rm=T) - mean(dat_long[dat_long$personal_force==1 & dat_long$intention==0,]$rate,na.rm=T)) - (mean(dat_long[dat_long$personal_force==0 & dat_long$intention==1,]$rate,na.rm=T) - mean(dat_long[dat_long$personal_force==1 & dat_long$intention==1,]$rate,na.rm=T)),2) 
}
studys2b_results = rbind(tabledata_s2b, tabledata_s2b_ne)
rownames(studys2b_results) <- NULL
studys2b_results[studys2b_results==0.000]<-"<.001"
studys2b_results[,"RR"]<-c("4.90e-02, 0.69", "5.10e-02, 0.63", "3.60e-02, 1.10", "2.60e-02, 0.72", "2.50e-02, 0.95", "1.40e-02, 1.30")


kbl(
  studys2b_results,
  format = "latex",
  booktabs = T,
  escape=T,
  caption = "Do personal force interact with intention on Speedboat dilemmas?",
  centering=T,
  position="H"
  )%>%
  kable_styling( full_width = F,  position="left", latex_options = "scale_down")%>%
  row_spec(row=0, bold=TRUE)%>%
  collapse_rows(columns = 1, valign = "top", latex_hline = "major", row_group_label_position = "identity")
```

<!-- //graph with exclusion -->
```{r study2b excl graph, fig.pos="H",out.width="80%",fig.cap="Results on the Speedboat dilemmas in Study 2 when all exclusion criteria are applied. Error bars are 95\\% confidence intervals on the mean.",  echo =FALSE,message=FALSE, warning=FALSE, paged.print=FALSE }
# Prepare data for plotting
plot_data <- 
  study2b %>% 
  select(survey_name, speedboat_3_rate, speedboat_4_rate, speedboat_5_rate, speedboat_6_rate) %>% 
  mutate(survey_name = factor(survey_name)) %>% 
  pivot_longer(
    -survey_name,
    names_to = "condition",
    values_to = "rate") %>% 
  mutate(personal_force = case_when(condition == "speedboat_3_rate" ~ "No Personal Force",
                                    condition == "speedboat_4_rate" ~ "Personal force",
                                    condition == "speedboat_5_rate" ~ "No Personal Force",
                                    condition == "speedboat_6_rate" ~ "Personal force"),
         intention = case_when(condition == "speedboat_3_rate" ~ "No Intention",
                               condition == "speedboat_4_rate" ~ "Intention",
                               condition == "speedboat_5_rate" ~ "Intention",
                               condition == "speedboat_6_rate" ~ "No Intention"),
         intention = factor(intention, levels = c("No Intention", "Intention")),
         survey_name = str_remove(survey_name, "PSA006_")) %>% 
  drop_na(rate)

# Create plot
plot_data %>% 
  ggplot() +
  aes(
    x = intention,
    y = rate,
    fill = personal_force,
    width = 0.7) +
  stat_summary(
    fun = mean,
    geom = "bar",
    position = "dodge",
    colour = "Black",
    width = 1.2) +
  stat_summary(
    fun.data = mean_cl_boot,
    geom = "errorbar",
    position = position_dodge(width = 0.7),
    colour = "Black",
    width = 0.2) +
  scale_fill_viridis_d() +
  facet_wrap(facets=vars(survey_name)) +
  labs(y = "To what extent is this action morally acceptable?") +
  theme_bw() +
  expand_limits(y = c(1,9)) +
  scale_y_continuous(breaks = 1:9) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_text(hjust = 0.5, vjust = 0.5, face = "bold", size = 17),
    axis.title.x = element_blank(),
    axis.title.y = element_text(face = "bold", size = 10),
    axis.text.x = element_text(face = "bold", size = 7, colour = "Black"),
    axis.text.y = element_text(face = "bold", size = 12, colour = "Black"),
    legend.title = element_blank(),
    legend.text = element_text(size = 9))
```


<!-- //graph without exclusion -->
```{r study2b w/o excl graph,fig.pos="H",out.width="80%",fig.cap="Results on the Speedboat dilemmas in Study 2 when no exclusion criteria is applied. Error bars are 95\\% confidence intervals on the mean.", echo =FALSE,message=FALSE, warning=FALSE, paged.print=FALSE }
# Prepare data for plotting
plot_data <- 
  trolley_proc %>% 
  select(survey_name, speedboat_3_rate, speedboat_4_rate, speedboat_5_rate, speedboat_6_rate) %>% 
  mutate(survey_name = factor(survey_name)) %>% 
  pivot_longer(
    -survey_name,
    names_to = "condition",
    values_to = "rate") %>% 
  mutate(personal_force = case_when(condition == "speedboat_3_rate" ~ "No Personal Force",
                                    condition == "speedboat_4_rate" ~ "Personal force",
                                    condition == "speedboat_5_rate" ~ "No Personal Force",
                                    condition == "speedboat_6_rate" ~ "Personal force"),
         intention = case_when(condition == "speedboat_3_rate" ~ "No Intention",
                               condition == "speedboat_4_rate" ~ "Intention",
                               condition == "speedboat_5_rate" ~ "Intention",
                               condition == "speedboat_6_rate" ~ "No Intention"),
         intention = factor(intention, levels = c("No Intention", "Intention")),
         survey_name = str_remove(survey_name, "PSA006_")) %>% 
  drop_na(rate)

# Create plot
plot_data %>% 
  ggplot() +
  aes(
    x = intention,
    y = rate,
    fill = personal_force,
    width = 0.7) +
  stat_summary(
    fun = mean,
    geom = "bar",
    position = "dodge",
    colour = "Black",
    width = 1.2) +
  stat_summary(
    fun.data = mean_cl_boot,
    geom = "errorbar",
    position = position_dodge(width = 0.7),
    colour = "Black",
    width = 0.2) +
  scale_fill_viridis_d() +
  facet_wrap(facets=vars(survey_name)) +
  labs(y = "To what extent is this action morally acceptable?") +
  theme_bw() +
  expand_limits(y = c(1,9)) +
  scale_y_continuous(breaks = 1:9) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_text(hjust = 0.5, vjust = 0.5, face = "bold", size = 17),
    axis.title.x = element_blank(),
    axis.title.y = element_text(face = "bold", size = 10),
    axis.text.x = element_text(face = "bold", size = 7, colour = "Black"),
    axis.text.y = element_text(face = "bold", size = 12, colour = "Black"),
    legend.title = element_blank(),
    legend.text = element_text(size = 9))
```


#3. Individualism-collectivism analysis

##With all exclusions

<!-- Bayesian country level individualism w/o exclusion -->
```{r analysis individual + country level study 2a, echo =FALSE,message=FALSE, warning=FALSE, paged.print=FALSE}


vars=c("Collectivism", "ver_ind", "hor_ind", "ver_col", "hor_col")
tabledata_s2a_ind = data.frame(variable=c("Country-level collectivism", "Vertical Individualism", "Horizontal Individualism", "Vertical Collectivism", "Horizontal Collectivism"), matrix(nrow=5, ncol=3, dimnames=list(vars,c("BF", "b",  "p"))))

dat=subset(study2a,  select=c("trolley_3_rate", "trolley_4_rate", "trolley_5_rate", "trolley_6_rate", "country3", vars))
dat_long=na.omit(melt(data=dat, variable.name = "condition", value.name="rate", id.vars=c(vars, "country3")))
dat_long$personal_force = factor(ifelse(dat_long$condition=="trolley_3_rate"|dat_long$condition=="trolley_5_rate", 0, 1))
dat_long$intention = factor(ifelse(dat_long$condition=="trolley_4_rate"|dat_long$condition=="trolley_5_rate", 1, 0))
dat_long$country3=as.character(dat_long$country3)
dat_long$country3=factor(paste0("0", dat_long$country3))

graphdata=data.frame(variable=c("Country-level collectivism", "Vertical Individualism", "Horizontal Individualism", "Vertical Collectivism", "Horizontal Collectivism"), matrix(nrow=5, ncol=3, dimnames=list(vars,c("b",  "lower", "higher"))))

for (i in vars){
  if(i=="Collectivism"){
  datt=lmBF(rate ~   personal_force*intention*Collectivism + country3, data=dat_long, whichRandom="country3",rscaleCont = c("personal_force:intention:Collectivism" = 0.19))
  datt2=lmBF(rate ~  personal_force+intention+Collectivism+personal_force:Collectivism+personal_force:intention+intention:Collectivism+country3, whichRandom="country3",data=dat_long)  
  frequentist_m=lmer(rate ~ personal_force*intention*Collectivism +(1|country3), data=dat_long)
  frequentist=broom.mixed::tidy(frequentist_m)
  } else if(i=="ver_ind"){
  datt=lmBF(rate ~   personal_force*intention*ver_ind+country3, data=dat_long,  whichRandom="country3",  rscaleCont = c("personal_force:intention:ver_ind" = 0.19))
  datt2=lmBF(rate ~ personal_force+intention+ver_ind+personal_force:ver_ind+personal_force:intention+intention:ver_ind +country3,  whichRandom="country3", data=dat_long)  
  frequentist_m=lmer(rate ~ personal_force*intention*ver_ind +(1|country3), data=dat_long)
  frequentist=broom.mixed::tidy(frequentist_m)
  }else if(i=="hor_ind"){
  datt=lmBF(rate ~   personal_force*intention*hor_ind+country3, data=dat_long,  whichRandom="country3", rscaleCont = c("personal_force:intention:hor_ind" = 0.19))
  datt2=lmBF(rate ~  personal_force+intention+hor_ind+personal_force:hor_ind+personal_force:intention+intention:hor_ind+country3,  whichRandom="country3", data=dat_long)  
  frequentist_m=lmer(rate ~ personal_force*intention*hor_ind +(1|country3), data=dat_long)
  frequentist=broom.mixed::tidy(frequentist_m)
  }else if(i=="ver_col"){
  datt=lmBF(rate ~   personal_force*intention*ver_col+country3, data=dat_long,  whichRandom="country3", rscaleCont = c("personal_force:intention:ver_col" = 0.19))
  datt2=lmBF(rate ~  personal_force+intention+ver_col+personal_force:ver_col+personal_force:intention+intention:ver_col +country3,  whichRandom="country3",  data=dat_long)  
  frequentist_m=lmer(rate ~ personal_force*intention*ver_col +(1|country3), data=dat_long)
  frequentist=broom.mixed::tidy(frequentist_m)
  }else if(i=="hor_col"){
  datt=lmBF(rate ~  personal_force*intention*hor_col+country3, data=dat_long, whichRandom="country3", rscaleCont = c("personal_force:intention:hor_col" = 0.19))
  datt2=lmBF(rate ~  personal_force+intention+hor_col+personal_force:hor_col+personal_force:intention+intention:hor_col +country3,  whichRandom="country3",   data=dat_long)  
  frequentist_m=lmer(rate ~ personal_force*intention*hor_col +(1|country3), data=dat_long)
  frequentist=broom.mixed::tidy(frequentist_m)
  }
datt3=datt/datt2
datt3=as_tibble(recompute(datt3, iterations = 50000))
tabledata_s2a_ind[i, "BF"]=signif(datt3[1,1],4)
tabledata_s2a_ind[i, "b"]=round(frequentist[8, "estimate"],3)
tabledata_s2a_ind[i, "p"]=round(frequentist[8, "p.value"],3)
graphdata[i, "b"]=round(frequentist[8, "estimate"],3)
graphdata[i, "lower"]=round(confint(frequentist_m),2)[10,1]
graphdata[i, "higher"]=round(confint(frequentist_m),2)[10,2]

}

graphdata=graphdata[-1,]
rownames(tabledata_s2a_ind) <- NULL


kbl(
  tabledata_s2a_ind,
  format = "latex",
  booktabs = T,
  escape=T,
  caption = "Is the interaction of personal force and intention affected by individualism/collectivism on Trolley dilemmas?",
  centering=T,
  position="H"
  )%>%
  kable_styling( full_width = F,  position="left")%>%
  row_spec(row=0, bold=TRUE)

```


```{r study2a overall individualism plot, fig.pos="H",out.width="80%",fig.cap="Correlation between country-level individualism/collectivism and the effect of personal force in Eta sqaured on the Trolley dilemmas", echo =FALSE,message=FALSE, warning=FALSE, paged.print=FALSE}
##cohen d calculation for every country
#scatterplot: x effect size, y individualism
#size of dots: cohen d
countrydata=data.frame(country=levels(factor(study2a$country3)), matrix(nrow=length(levels(factor(study2a$country3))),ncol=3, dimnames=list(levels(factor(study2a$country3)), c("cohend","Collectivism","N") )))

for (i in levels(factor(study2a$country3))){
  d=subset(study2a, country3==i, select=c("trolley_3_rate", "trolley_4_rate", "trolley_5_rate", "trolley_6_rate"))
  dat_long=na.omit(melt(data=d, variable.name = "condition", value.name="rate"))
  dat_long$personal_force = factor(ifelse(dat_long$condition=="trolley_3_rate"|dat_long$condition=="trolley_5_rate", 0, 1))
  dat_long$intention = factor(ifelse(dat_long$condition=="trolley_4_rate"|dat_long$condition=="trolley_5_rate", 1, 0))
  if (length(dat_long$rate)<10){
    countrydata[i,"cohend"]=NA
  }else{
    countrydata[i,"cohend"]=effectsize::eta_squared(aov(rate~intention:personal_force, data=dat_long))$Eta2
  }
  countrydata[i,"Collectivism"]=mean(study2a[study2a$country3==i,]$Collectivism, na.rm=T)
  countrydata[i,"N"]=length(dat_long$rate)
}

countrydata=na.omit(countrydata)
ggplot(countrydata, aes(x=cohend, y=Collectivism, label=country)) +
  geom_point(aes(size=N))+
  geom_text(hjust=-0.2,size=3)+
geom_smooth(method = "lm", mapping = aes(weight = N), color = "blue", show.legend = FALSE, se=F)+xlab("Effect size")+
  theme_bw()+
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),plot.title=element_text( hjust=0.5, vjust=0.5, face="bold", size=17),
        axis.title.x=element_text(face="bold", size=12, colour="Black"), axis.title.y=element_text(face="bold", size=12, colour="Black"), axis.text.x = element_text(face="bold", size=10, colour="Black"), axis.text.y = element_text(face="bold", size=12, colour="Black"),
        legend.title=element_text(face="bold", size=10, colour="Black"),legend.text=element_text(size=9))
  
  

```


<!-- Bayesian personal level individualism  w/o exclusion-->
```{r study2a vertical horizontal individualism, out.width="80%", fig.cap="Personal level individualism/collectivism effects on the interaction of personal force and intention (trolley dilemmas)", echo =FALSE,message=FALSE, warning=FALSE, paged.print=FALSE}


ggplot(graphdata, aes(x=variable, y=b, width=0.7)) +
 geom_bar(stat="identity", position="dodge", colour="Black",  width=1.2)+
  geom_errorbar(aes(ymin=lower, ymax=higher), position=position_dodge(width=0.7), colour="Black", width=0.2) +
  labs( y="Beta effect size")+ theme_bw()+
  geom_hline(yintercept=0)+
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),plot.title=element_text( hjust=0.5, vjust=0.5, face="bold", size=17),
        axis.title.x=element_blank(), axis.title.y=element_text(face="bold", size=10), axis.text.x = element_text(face="bold", size=7, colour="Black"), axis.text.y = element_text(face="bold", size=12, colour="Black"),
        legend.title=element_blank(),legend.text=element_text(size=9))


```


<!-- Bayesian country level individualism w/o exclusion -->
```{r analysis individual + country level study 2b, echo =FALSE,message=FALSE, warning=FALSE, paged.print=FALSE}
#for loop changes predictor variables
#table has 5lines: country level individualism, then individual level measures

vars=c("Collectivism", "ver_ind", "hor_ind", "ver_col", "hor_col")
tabledata_s2b_ind = data.frame(variable=c("Country-level collectivism", "Vertical Individualism", "Horizontal Individualism", "Vertical Collectivism", "Horizontal Collectivism"), matrix(nrow=5, ncol=3, dimnames=list(vars,c("BF", "b",  "p"))))

graphdata=data.frame(variable=c("Country-level collectivism", "Vertical Individualism", "Horizontal Individualism", "Vertical Collectivism", "Horizontal Collectivism"), matrix(nrow=5, ncol=3, dimnames=list(vars,c("b",  "lower", "higher"))))


dat=subset(study2b,  select=c("speedboat_3_rate", "speedboat_4_rate", "speedboat_5_rate", "speedboat_6_rate", "country3", vars))
dat_long=na.omit(melt(data=dat, variable.name = "condition", value.name="rate", id.vars=c(vars, "country3")))
dat_long$personal_force = factor(ifelse(dat_long$condition=="speedboat_3_rate"|dat_long$condition=="speedboat_5_rate", 0, 1))
dat_long$intention = factor(ifelse(dat_long$condition=="speedboat_4_rate"|dat_long$condition=="speedboat_5_rate", 1, 0))
dat_long$country3=as.character(dat_long$country3)
dat_long$country3=factor(paste0("0", dat_long$country3))


for (i in vars){
  if(i=="Collectivism"){
  datt=lmBF(rate ~   personal_force*intention*Collectivism + country3, data=dat_long, whichRandom="country3",rscaleCont = c("personal_force:intention:Collectivism" = 0.19))
  datt2=lmBF(rate ~  personal_force+intention+Collectivism+personal_force:Collectivism+personal_force:intention+intention:Collectivism+country3, whichRandom="country3",data=dat_long)  
  frequentist_m=lmer(rate ~ personal_force*intention*Collectivism +(1|country3), data=dat_long)
  frequentist=broom.mixed::tidy(frequentist_m)
  } else if(i=="ver_ind"){
  datt=lmBF(rate ~   personal_force*intention*ver_ind+country3, data=dat_long,  whichRandom="country3",  rscaleCont = c("personal_force:intention:ver_ind" = 0.19))
  datt2=lmBF(rate ~ personal_force+intention+ver_ind+personal_force:ver_ind+personal_force:intention+intention:ver_ind +country3,  whichRandom="country3", data=dat_long)  
  frequentist_m=lmer(rate ~ personal_force*intention*ver_ind +(1|country3), data=dat_long)
  frequentist=broom.mixed::tidy(frequentist_m)
  }else if(i=="hor_ind"){
  datt=lmBF(rate ~   personal_force*intention*hor_ind+country3, data=dat_long,  whichRandom="country3", rscaleFixed=0.26, rscaleCont = c("personal_force:intention:hor_ind" = 0.19))
  datt2=lmBF(rate ~  personal_force+intention+hor_ind+personal_force:hor_ind+personal_force:intention+intention:hor_ind+country3,  whichRandom="country3", data=dat_long)  
  frequentist_m=lmer(rate ~ personal_force*intention*hor_ind +(1|country3), data=dat_long)
  frequentist=broom.mixed::tidy(frequentist_m)
  }else if(i=="ver_col"){
  datt=lmBF(rate ~   personal_force*intention*ver_col+country3, data=dat_long,  whichRandom="country3", rscaleCont = c("personal_force:intention:ver_col" = 0.19))
  datt2=lmBF(rate ~  personal_force+intention+ver_col+personal_force:ver_col+personal_force:intention+intention:ver_col +country3,  whichRandom="country3",  data=dat_long)  
  frequentist_m=lmer(rate ~ personal_force*intention*ver_col +(1|country3), data=dat_long)
  frequentist=broom.mixed::tidy(frequentist_m)
  }else if(i=="hor_col"){
  datt=lmBF(rate ~  personal_force*intention*hor_col+country3, data=dat_long, whichRandom="country3", rscaleCont = c("personal_force:intention:hor_col" = 0.19))
  datt2=lmBF(rate ~  personal_force+intention+hor_col+personal_force:hor_col+personal_force:intention+intention:hor_col +country3,  whichRandom="country3",   data=dat_long)  
  frequentist_m=lmer(rate ~ personal_force*intention*hor_col +(1|country3), data=dat_long)
  frequentist=broom.mixed::tidy(frequentist_m)
  }
datt3=datt/datt2
datt3=as_tibble(recompute(datt3, iterations = 50000))
tabledata_s2b_ind[i, "BF"]=signif(datt3[1,1],4)
tabledata_s2b_ind[i, "b"]=round(frequentist[8, "estimate"],3)
tabledata_s2b_ind[i, "p"]=round(frequentist[8, "p.value"],3)
graphdata[i, "b"]=round(frequentist[8, "estimate"],3)
graphdata[i, "lower"]=round(confint(frequentist_m),2)[10,1]
graphdata[i, "higher"]=round(confint(frequentist_m),2)[10,2]

}

graphdata=graphdata[-1,]

rownames(tabledata_s2b_ind) <- NULL

kbl(
  tabledata_s2b_ind,
  format = "latex",
  booktabs = T,
  escape=T,
  caption = "Is the interaction of personal force and intention affected by individualism/collectivism on Speedboat dilemmas?",
  centering=T,
  position="H"
  )%>%
  kable_styling( full_width = F,  position="left")%>%
  row_spec(row=0, bold=TRUE)



```


```{r study2b overall individualism plot, fig.pos="H",out.width="80%",fig.cap="Correlation between country-level individualism/collectivism and the interactional effect of personal force and intention in Eta squared on Speedboat dilemmas", echo =FALSE,message=FALSE, warning=FALSE, paged.print=FALSE}
##cohen d calculation for every country
#scatterplot: x effect size, y individualism
#size of dots: cohen d
countrydata=data.frame(country=levels(factor(study2b$country3)), matrix(nrow=length(levels(factor(study2b$country3))),ncol=3, dimnames=list(levels(factor(study2b$country3)), c("cohend","Collectivism","N") )))

for (i in levels(factor(study2b$country3))){
  d=subset(study2b, country3==i, select=c("speedboat_3_rate", "speedboat_4_rate", "speedboat_5_rate", "speedboat_6_rate"))
  dat_long=na.omit(melt(data=d, variable.name = "condition", value.name="rate"))
  dat_long$personal_force = factor(ifelse(dat_long$condition=="speedboat_3_rate"|dat_long$condition=="speedboat_5_rate", 0, 1))
  dat_long$intention = factor(ifelse(dat_long$condition=="speedboat_4_rate"|dat_long$condition=="speedboat_5_rate", 1, 0))
  if (length(dat_long$rate)<10){
    countrydata[i,"cohend"]=NA
  }else{
    countrydata[i,"cohend"]=effectsize::eta_squared(aov(rate~intention:personal_force, data=dat_long))$Eta2
  }
  countrydata[i,"Collectivism"]=mean(study2b[study2b$country3==i,]$Collectivism, na.rm=T)
  countrydata[i,"N"]=length(dat_long$rate)
}

countrydata=na.omit(countrydata)
ggplot(countrydata, aes(x=cohend, y=Collectivism, label=country)) +
  geom_point(aes(size=N))+
  geom_text(hjust=-0.2,size=3)+
  geom_smooth(method = "lm", mapping = aes(weight = N), color = "blue", show.legend = FALSE, se=F)+
  xlab("Effect size")+
  theme_bw()+
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),plot.title=element_text( hjust=0.5, vjust=0.5, face="bold", size=17),
        axis.title.x=element_text(face="bold", size=12, colour="Black"), axis.title.y=element_text(face="bold", size=12, colour="Black"), axis.text.x = element_text(face="bold", size=10, colour="Black"), axis.text.y = element_text(face="bold", size=12, colour="Black"),
        legend.title=element_text(face="bold", size=10, colour="Black"),legend.text=element_text(size=9))
  
  

```


<!-- Bayesian personal level individualism  w/o exclusion-->
```{r study2b vertical horizontal individualism,  out.width="80%", fig.cap="Personal level individualism/collectivism effects on the interaction of personal force and intention (speedboat dilemmas)", echo =FALSE,message=FALSE, warning=FALSE, paged.print=FALSE}


ggplot(graphdata, aes(x=variable, y=b, width=0.7)) +
 geom_bar(stat="identity", position="dodge", colour="Black",  width=1.2)+
  geom_errorbar(aes(ymin=lower, ymax=higher), position=position_dodge(width=0.7), colour="Black", width=0.2) +
  labs( y="Beta effect size")+ theme_bw()+
  geom_hline(yintercept=0)+
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),plot.title=element_text( hjust=0.5, vjust=0.5, face="bold", size=17),
        axis.title.x=element_blank(), axis.title.y=element_text(face="bold", size=10), axis.text.x = element_text(face="bold", size=7, colour="Black"), axis.text.y = element_text(face="bold", size=12, colour="Black"),
        legend.title=element_blank(),legend.text=element_text(size=9))



```

##Including familiar participants

```{r analysis individual + country level study 2a w familiar, echo =FALSE,message=FALSE, warning=FALSE, paged.print=FALSE}
#for loop changes predictor variables
#table has 5lines: country level individualism, then individual level measures

vars=c("Collectivism", "ver_ind", "hor_ind", "ver_col", "hor_col")
tabledata_s2a_ind = data.frame(variable=c("Country-level collectivism", "Vertical Individualism", "Horizontal Individualism", "Vertical Collectivism", "Horizontal Collectivism"), matrix(nrow=5, ncol=3, dimnames=list(vars,c("BF", "b",  "p"))))

dat=subset(trolley_proc,  select=c("trolley_3_rate", "trolley_4_rate", "trolley_5_rate", "trolley_6_rate", "country3", vars))
dat_long=na.omit(melt(data=dat, variable.name = "condition", value.name="rate", id.vars=c(vars, "country3")))
dat_long$personal_force = factor(ifelse(dat_long$condition=="trolley_3_rate"|dat_long$condition=="trolley_5_rate", 0, 1))
dat_long$intention = factor(ifelse(dat_long$condition=="trolley_4_rate"|dat_long$condition=="trolley_5_rate", 1, 0))
dat_long$country3=as.character(dat_long$country3)
dat_long$country3=factor(paste0("0", dat_long$country3))

graphdata=data.frame(variable=c("Country-level collectivism", "Vertical Individualism", "Horizontal Individualism", "Vertical Collectivism", "Horizontal Collectivism"), matrix(nrow=5, ncol=3, dimnames=list(vars,c("b",  "lower", "higher"))))

for (i in vars){
  if(i=="Collectivism"){
  datt=lmBF(rate ~   personal_force*intention*Collectivism + country3, data=dat_long, whichRandom="country3",rscaleCont = c("personal_force:intention:Collectivism" = 0.19))
  datt2=lmBF(rate ~  personal_force+intention+Collectivism+personal_force:Collectivism+personal_force:intention+intention:Collectivism+country3, whichRandom="country3",data=dat_long)  
  frequentist_m=lmer(rate ~ personal_force*intention*Collectivism +(1|country3), data=dat_long)
  frequentist=broom.mixed::tidy(frequentist_m)
  } else if(i=="ver_ind"){
  datt=lmBF(rate ~   personal_force*intention*ver_ind+country3, data=dat_long,  whichRandom="country3",  rscaleCont = c("personal_force:intention:ver_ind" = 0.19))
  datt2=lmBF(rate ~ personal_force+intention+ver_ind+personal_force:ver_ind+personal_force:intention+intention:ver_ind +country3,  whichRandom="country3", data=dat_long)  
  frequentist_m=lmer(rate ~ personal_force*intention*ver_ind +(1|country3), data=dat_long)
  frequentist=broom.mixed::tidy(frequentist_m)
  }else if(i=="hor_ind"){
  datt=lmBF(rate ~   personal_force*intention*hor_ind+country3, data=dat_long,  whichRandom="country3", rscaleFixed=0.26, rscaleCont = c("personal_force:intention:hor_ind" = 0.19))
  datt2=lmBF(rate ~  personal_force+intention+hor_ind+personal_force:hor_ind+personal_force:intention+intention:hor_ind+country3,  whichRandom="country3", data=dat_long)  
  frequentist_m=lmer(rate ~ personal_force*intention*hor_ind +(1|country3), data=dat_long)
  frequentist=broom.mixed::tidy(frequentist_m)
  }else if(i=="ver_col"){
  datt=lmBF(rate ~   personal_force*intention*ver_col+country3, data=dat_long,  whichRandom="country3", rscaleCont = c("personal_force:intention:ver_col" = 0.19))
  datt2=lmBF(rate ~  personal_force+intention+ver_col+personal_force:ver_col+personal_force:intention+intention:ver_col +country3,  whichRandom="country3",  data=dat_long)  
  frequentist_m=lmer(rate ~ personal_force*intention*ver_col +(1|country3), data=dat_long)
  frequentist=broom.mixed::tidy(frequentist_m)
  }else if(i=="hor_col"){
  datt=lmBF(rate ~  personal_force*intention*hor_col+country3, data=dat_long, whichRandom="country3", rscaleCont = c("personal_force:intention:hor_col" = 0.19))
  datt2=lmBF(rate ~  personal_force+intention+hor_col+personal_force:hor_col+personal_force:intention+intention:hor_col +country3,  whichRandom="country3",   data=dat_long)  
  frequentist_m=lmer(rate ~ personal_force*intention*hor_col +(1|country3), data=dat_long)
  frequentist=broom.mixed::tidy(frequentist_m)
  }
datt3=datt/datt2
datt3=as_tibble(recompute(datt3, iterations = 50000))
tabledata_s2a_ind[i, "BF"]=signif(datt3[1,1],4)
tabledata_s2a_ind[i, "b"]=round(frequentist[8, "estimate"],3)
tabledata_s2a_ind[i, "p"]=round(frequentist[8, "p.value"],3)
graphdata[i, "b"]=round(frequentist[8, "estimate"],3)
graphdata[i, "lower"]=round(confint(frequentist_m),2)[10,1]
graphdata[i, "higher"]=round(confint(frequentist_m),2)[10,2]

}

graphdata=graphdata[-1,]
rownames(tabledata_s2a_ind) <- NULL


kbl(
  tabledata_s2a_ind,
  format = "latex",
  booktabs = T,
  escape=T,
  caption = "Is the interaction of personal force and intention affected by individualism/collectivism on Trolley dilemmas?",
  centering=T,
  position="H"
  )%>%
  kable_styling( full_width = F,  position="left")%>%
  row_spec(row=0, bold=TRUE)

```


```{r study2a overall individualism plot w familiar, fig.pos="H",out.width="80%",fig.cap="Correlation between country-level individualism/collectivism and the effect of personal force in Eta sqaured on the Trolley dilemmas", echo =FALSE,message=FALSE, warning=FALSE, paged.print=FALSE}
##cohen d calculation for every country
#scatterplot: x effect size, y individualism
#size of dots: cohen d
countrydata=data.frame(country=levels(factor(trolley_proc$country3)), matrix(nrow=length(levels(factor(trolley_proc$country3))),ncol=3, dimnames=list(levels(factor(trolley_proc$country3)), c("cohend","Collectivism","N") )))

for (i in levels(factor(trolley_proc$country3))){
  d=subset(trolley_proc, country3==i, select=c("trolley_3_rate", "trolley_4_rate", "trolley_5_rate", "trolley_6_rate"))
  dat_long=na.omit(melt(data=d, variable.name = "condition", value.name="rate"))
  dat_long$personal_force = factor(ifelse(dat_long$condition=="trolley_3_rate"|dat_long$condition=="trolley_5_rate", 0, 1))
  dat_long$intention = factor(ifelse(dat_long$condition=="trolley_4_rate"|dat_long$condition=="trolley_5_rate", 1, 0))
  if (length(dat_long$rate)<10){
    countrydata[i,"cohend"]=NA
  }else{
    countrydata[i,"cohend"]=effectsize::eta_squared(aov(rate~intention:personal_force, data=dat_long))$Eta2
  }
  countrydata[i,"Collectivism"]=mean(trolley_proc[trolley_proc$country3==i,]$Collectivism, na.rm=T)
  countrydata[i,"N"]=length(dat_long$rate)
}

countrydata=na.omit(countrydata)
ggplot(countrydata, aes(x=cohend, y=Collectivism, label=country)) +
  geom_point(aes(size=N))+
  geom_text(hjust=-0.2,size=3)+
geom_smooth(method = "lm", mapping = aes(weight = N), color = "blue", show.legend = FALSE, se=F)+xlab("Effect size")+
  theme_bw()+
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),plot.title=element_text( hjust=0.5, vjust=0.5, face="bold", size=17),
        axis.title.x=element_text(face="bold", size=12, colour="Black"), axis.title.y=element_text(face="bold", size=12, colour="Black"), axis.text.x = element_text(face="bold", size=10, colour="Black"), axis.text.y = element_text(face="bold", size=12, colour="Black"),
        legend.title=element_text(face="bold", size=10, colour="Black"),legend.text=element_text(size=9))
  
  

```


```{r study2a vertical horizontal individualism w familiar, out.width="80%", fig.cap="Personal level individualism/collectivism effects on the interaction of personal force and intention (trolley dilemmas)", echo =FALSE,message=FALSE, warning=FALSE, paged.print=FALSE}


ggplot(graphdata, aes(x=variable, y=b, width=0.7)) +
 geom_bar(stat="identity", position="dodge", colour="Black",  width=1.2)+
  geom_errorbar(aes(ymin=lower, ymax=higher), position=position_dodge(width=0.7), colour="Black", width=0.2) +
  labs( y="Beta effect size")+ theme_bw()+
  geom_hline(yintercept=0)+
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),plot.title=element_text( hjust=0.5, vjust=0.5, face="bold", size=17),
        axis.title.x=element_blank(), axis.title.y=element_text(face="bold", size=10), axis.text.x = element_text(face="bold", size=7, colour="Black"), axis.text.y = element_text(face="bold", size=12, colour="Black"),
        legend.title=element_blank(),legend.text=element_text(size=9))


```


```{r analysis individual + country level study 2b w familiar, echo =FALSE,message=FALSE, warning=FALSE, paged.print=FALSE}
#for loop changes predictor variables
#table has 5lines: country level individualism, then individual level measures

vars=c("Collectivism", "ver_ind", "hor_ind", "ver_col", "hor_col")
tabledata_s2b_ind = data.frame(variable=c("Country-level collectivism", "Vertical Individualism", "Horizontal Individualism", "Vertical Collectivism", "Horizontal Collectivism"), matrix(nrow=5, ncol=3, dimnames=list(vars,c("BF", "b",  "p"))))

graphdata=data.frame(variable=c("Country-level collectivism", "Vertical Individualism", "Horizontal Individualism", "Vertical Collectivism", "Horizontal Collectivism"), matrix(nrow=5, ncol=3, dimnames=list(vars,c("b",  "lower", "higher"))))


dat=subset(trolley_proc,  select=c("speedboat_3_rate", "speedboat_4_rate", "speedboat_5_rate", "speedboat_6_rate", "country3", vars))
dat_long=na.omit(melt(data=dat, variable.name = "condition", value.name="rate", id.vars=c(vars, "country3")))
dat_long$personal_force = factor(ifelse(dat_long$condition=="speedboat_3_rate"|dat_long$condition=="speedboat_5_rate", 0, 1))
dat_long$intention = factor(ifelse(dat_long$condition=="speedboat_4_rate"|dat_long$condition=="speedboat_5_rate", 1, 0))
dat_long$country3=as.character(dat_long$country3)
dat_long$country3=factor(paste0("0", dat_long$country3))


for (i in vars){
  if(i=="Collectivism"){
  datt=lmBF(rate ~   personal_force*intention*Collectivism + country3, data=dat_long, whichRandom="country3",rscaleCont = c("personal_force:intention:Collectivism" = 0.19))
  datt2=lmBF(rate ~  personal_force+intention+Collectivism+personal_force:Collectivism+personal_force:intention+intention:Collectivism+country3, whichRandom="country3",data=dat_long)  
  frequentist_m=lmer(rate ~ personal_force*intention*Collectivism +(1|country3), data=dat_long)
  frequentist=broom.mixed::tidy(frequentist_m)
  } else if(i=="ver_ind"){
  datt=lmBF(rate ~   personal_force*intention*ver_ind+country3, data=dat_long,  whichRandom="country3",  rscaleCont = c("personal_force:intention:ver_ind" = 0.19))
  datt2=lmBF(rate ~ personal_force+intention+ver_ind+personal_force:ver_ind+personal_force:intention+intention:ver_ind +country3,  whichRandom="country3", data=dat_long)  
  frequentist_m=lmer(rate ~ personal_force*intention*ver_ind +(1|country3), data=dat_long)
  frequentist=broom.mixed::tidy(frequentist_m)
  }else if(i=="hor_ind"){
  datt=lmBF(rate ~   personal_force*intention*hor_ind+country3, data=dat_long,  whichRandom="country3", rscaleCont = c("personal_force:intention:hor_ind" = 0.19))
  datt2=lmBF(rate ~  personal_force+intention+hor_ind+personal_force:hor_ind+personal_force:intention+intention:hor_ind+country3,  whichRandom="country3", data=dat_long)  
  frequentist_m=lmer(rate ~ personal_force*intention*hor_ind +(1|country3), data=dat_long)
  frequentist=broom.mixed::tidy(frequentist_m)
  }else if(i=="ver_col"){
  datt=lmBF(rate ~   personal_force*intention*ver_col+country3, data=dat_long,  whichRandom="country3", rscaleCont = c("personal_force:intention:ver_col" = 0.19))
  datt2=lmBF(rate ~  personal_force+intention+ver_col+personal_force:ver_col+personal_force:intention+intention:ver_col +country3,  whichRandom="country3",  data=dat_long)  
  frequentist_m=lmer(rate ~ personal_force*intention*ver_col +(1|country3), data=dat_long)
  frequentist=broom.mixed::tidy(frequentist_m)
  }else if(i=="hor_col"){
  datt=lmBF(rate ~  personal_force*intention*hor_col+country3, data=dat_long, whichRandom="country3", rscaleCont = c("personal_force:intention:hor_col" = 0.19))
  datt2=lmBF(rate ~  personal_force+intention+hor_col+personal_force:hor_col+personal_force:intention+intention:hor_col +country3,  whichRandom="country3",   data=dat_long)  
  frequentist_m=lmer(rate ~ personal_force*intention*hor_col +(1|country3), data=dat_long)
  frequentist=broom.mixed::tidy(frequentist_m)
  }
datt3=datt/datt2
datt3=as_tibble(recompute(datt3, iterations = 50000))
tabledata_s2b_ind[i, "BF"]=signif(datt3[1,1],4)
tabledata_s2b_ind[i, "b"]=round(frequentist[8, "estimate"],3)
tabledata_s2b_ind[i, "p"]=round(frequentist[8, "p.value"],3)
graphdata[i, "b"]=round(frequentist[8, "estimate"],3)
graphdata[i, "lower"]=round(confint(frequentist_m),2)[10,1]
graphdata[i, "higher"]=round(confint(frequentist_m),2)[10,2]

}

graphdata=graphdata[-1,]

rownames(tabledata_s2b_ind) <- NULL

kbl(
  tabledata_s2b_ind,
  format = "latex",
  booktabs = T,
  escape=T,
  caption = "Is the interaction of personal force and intention affected by individualism/collectivism on Speedboat dilemmas?",
  centering=T,
  position="H"
  )%>%
  kable_styling( full_width = F,  position="left")%>%
  row_spec(row=0, bold=TRUE)



```


```{r study2b overall individualism plot w familiar, fig.pos="H",out.width="80%",fig.cap="Correlation between country-level individualism/collectivism and the interactional effect of personal force and intention in Eta squared on Speedboat dilemmas", echo =FALSE,message=FALSE, warning=FALSE, paged.print=FALSE}
##cohen d calculation for every country
#scatterplot: x effect size, y individualism
#size of dots: cohen d
countrydata=data.frame(country=levels(factor(trolley_proc$country3)), matrix(nrow=length(levels(factor(trolley_proc$country3))),ncol=3, dimnames=list(levels(factor(trolley_proc$country3)), c("cohend","Collectivism","N") )))

for (i in levels(factor(trolley_proc$country3))){
  d=subset(trolley_proc, country3==i, select=c("speedboat_3_rate", "speedboat_4_rate", "speedboat_5_rate", "speedboat_6_rate"))
  dat_long=na.omit(melt(data=d, variable.name = "condition", value.name="rate"))
  dat_long$personal_force = factor(ifelse(dat_long$condition=="speedboat_3_rate"|dat_long$condition=="speedboat_5_rate", 0, 1))
  dat_long$intention = factor(ifelse(dat_long$condition=="speedboat_4_rate"|dat_long$condition=="speedboat_5_rate", 1, 0))
  if (length(dat_long$rate)<10){
    countrydata[i,"cohend"]=NA
  }else{
    countrydata[i,"cohend"]=effectsize::eta_squared(aov(rate~intention:personal_force, data=dat_long))$Eta2
  }
  countrydata[i,"Collectivism"]=mean(trolley_proc[trolley_proc$country3==i,]$Collectivism, na.rm=T)
  countrydata[i,"N"]=length(dat_long$rate)
}

countrydata=na.omit(countrydata)
ggplot(countrydata, aes(x=cohend, y=Collectivism, label=country)) +
  geom_point(aes(size=N))+
  geom_text(hjust=-0.2,size=3)+
  geom_smooth(method = "lm", mapping = aes(weight = N), color = "blue", show.legend = FALSE, se=F)+
  xlab("Effect size")+
  theme_bw()+
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),plot.title=element_text( hjust=0.5, vjust=0.5, face="bold", size=17),
        axis.title.x=element_text(face="bold", size=12, colour="Black"), axis.title.y=element_text(face="bold", size=12, colour="Black"), axis.text.x = element_text(face="bold", size=10, colour="Black"), axis.text.y = element_text(face="bold", size=12, colour="Black"),
        legend.title=element_text(face="bold", size=10, colour="Black"),legend.text=element_text(size=9))
  
  

```


```{r study2b vertical horizontal individualism w familiar,  out.width="80%", fig.cap="Personal level individualism/collectivism effects on the interaction of personal force and intention (speedboat dilemmas)", echo =FALSE,message=FALSE, warning=FALSE, paged.print=FALSE}


ggplot(graphdata, aes(x=variable, y=b, width=0.7)) +
 geom_bar(stat="identity", position="dodge", colour="Black",  width=1.2)+
  geom_errorbar(aes(ymin=lower, ymax=higher), position=position_dodge(width=0.7), colour="Black", width=0.2) +
  labs( y="Beta effect size")+ theme_bw()+
  geom_hline(yintercept=0)+
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank(),plot.title=element_text( hjust=0.5, vjust=0.5, face="bold", size=17),
        axis.title.x=element_blank(), axis.title.y=element_text(face="bold", size=10), axis.text.x = element_text(face="bold", size=7, colour="Black"), axis.text.y = element_text(face="bold", size=12, colour="Black"),
        legend.title=element_blank(),legend.text=element_text(size=9))



```


